export * from './types/message'
export * from './types/branding'
export * from './interfaces/email-template'
export * from './interfaces/email-service'
export { emailLayout, emailButton, formatDatePtBR, escapeHtml } from './templates/base-layout'
export { BrevoEmailAdapter } from './brevo/brevo-adapter'
export { TemplateRegistry } from './templates/registry'
export { welcomeTemplate, type WelcomeVars } from './templates/welcome'
export { inviteTemplate, type InviteVars } from './templates/invite'
export { confirmSubscriptionTemplate, type ConfirmSubscriptionVars } from './templates/confirm-subscription'
export { contactReceivedTemplate, type ContactReceivedVars } from './templates/contact-received'
export { contactAdminAlertTemplate, type ContactAdminAlertVars } from './templates/contact-admin-alert'
export { ensureUnsubscribeToken } from './helpers/unsubscribe-token'
export * as log from './debug'
