import type { HomeChannel, HomeVideo } from './types'

export const YOUTUBE_CHANNELS: Record<'en' | 'pt-BR', HomeChannel> = {
  'en': {
    id: 'UC_en_001',
    locale: 'en',
    handle: '@byThiagoFigueiredo',
    url: 'https://www.youtube.com/@byThiagoFigueiredo',
    flag: '🌎',
    name: 'by Thiago Figueiredo',
    subscriberCount: 0,
    thumbnailUrl: null,
  },
  'pt-BR': {
    id: 'UC_pt_001',
    locale: 'pt-BR',
    handle: '@tnFigueiredoTV',
    url: 'https://www.youtube.com/@tnFigueiredoTV',
    flag: '🇧🇷',
    name: 'tnFigueiredo TV',
    subscriberCount: 0,
    thumbnailUrl: null,
  },
}

// Placeholder data — replace with YouTube Data API v3 in a future sprint
export const SAMPLE_VIDEOS: HomeVideo[] = [
  {
    id: 'v1',
    locale: 'pt-BR',
    title: 'Como eu estruturo projetos Next.js em 2026',
    description: 'Arquitetura, pastas, patterns — tudo que aprendi em 5 anos de produção.',
    thumbnailUrl: null,
    duration: '18:42',
    viewCount: 0,
    publishedAt: '2026-04-10',
    categoryName: 'Dev Diary',
    categoryColor: null,
    youtubeUrl: 'https://www.youtube.com/@tnFigueiredoTV',
    channelHandle: '@tnFigueiredoTV',
    youtubeVideoId: 'v1',
    isPinned: false,
  },
  {
    id: 'v2',
    locale: 'pt-BR',
    title: 'Viagem de moto pelo RS — 3 dias, 900km',
    description: 'Da Serra Gaúcha ao litoral numa moto de 250cc. Vale a pena?',
    thumbnailUrl: null,
    duration: '24:15',
    viewCount: 0,
    publishedAt: '2026-03-28',
    categoryName: 'Estrada',
    categoryColor: null,
    youtubeUrl: 'https://www.youtube.com/@tnFigueiredoTV',
    channelHandle: '@tnFigueiredoTV',
    youtubeVideoId: 'v2',
    isPinned: false,
  },
  {
    id: 'v3',
    locale: 'en',
    title: 'Building a personal CMS from scratch',
    description: 'Why I wrote my own CMS instead of using Notion, Sanity, or Ghost.',
    thumbnailUrl: null,
    duration: '22:08',
    viewCount: 0,
    publishedAt: '2026-04-05',
    categoryName: 'Build in Public',
    categoryColor: null,
    youtubeUrl: 'https://www.youtube.com/@byThiagoFigueiredo',
    channelHandle: '@byThiagoFigueiredo',
    youtubeVideoId: 'v3',
    isPinned: false,
  },
  {
    id: 'v4',
    locale: 'en',
    title: 'The 1-year mark: what changed',
    description: "A year of creating in public. What worked, what flopped, what's next.",
    thumbnailUrl: null,
    duration: '15:30',
    viewCount: 0,
    publishedAt: '2026-03-15',
    categoryName: 'Build in Public',
    categoryColor: null,
    youtubeUrl: 'https://www.youtube.com/@byThiagoFigueiredo',
    channelHandle: '@byThiagoFigueiredo',
    youtubeVideoId: 'v4',
    isPinned: false,
  },
]
