// Content-side (blog-first) content for bythiagofigueiredo homepage.
// Inspired by brightcurios.com structure: hero post, category grids,
// most-read sidebar, YouTube row, inline newsletter.

// Color-coded placeholder images (abstract gradients, no real photos yet).
// Caller renders them as CSS gradients using {h, h2, pattern} hints.

window.CONTENT = {
  categories: {
    code:       { pt: "Código",        en: "Code",        color: "#D65B1F", hue: 18 },
    product:    { pt: "Produto",       en: "Product",     color: "#2F6B22", hue: 110 },
    essay:      { pt: "Ensaios",       en: "Essays",      color: "#1E4D7A", hue: 210 },
    diary:      { pt: "Diário",        en: "Journal",     color: "#8A4A8F", hue: 290 },
    tools:      { pt: "Ferramentas",   en: "Tools",       color: "#B87333", hue: 32 },
    career:     { pt: "Carreira",      en: "Career",      color: "#5B6E2B", hue: 75 },
  },

  // 14 posts, most recent first, with category refs
  posts: [
    {
      slug: "manifesto-bythiagofigueiredo",
      cat: "essay",
      date_pt: "24 Abr 2026", date_en: "Apr 24, 2026", iso: "2026-04-24",
      updated_pt: "26 Abr 2026", updated_en: "Apr 26, 2026", iso_updated: "2026-04-26",
      read: "9",
      tags: ["meta", "manifesto", "2026", "hub"], feat: false,
      img: { h: 28, h2: 52, pattern: "blur" },
      heroIllustration: "constellation",
      series: { id: "meta", total: 3, current: 1,
                title_pt: "Construindo em público: o próprio projeto",
                title_en: "Building in public: the project itself",
                prev: null, next: "um-cms-para-governar" },
      title_pt: "Por que existe bythiagofigueiredo — e o que ele não é",
      title_en: "Why bythiagofigueiredo exists — and what it isn't",
      excerpt_pt: "Um manifesto honesto sobre o porquê desse lugar existir, o que você vai encontrar aqui, e as três coisas que eu prometi a mim mesmo nunca fazer.",
      excerpt_en: "An honest manifesto about why this place exists, what you'll find here, and the three things I promised myself I'd never do.",
    },
    {
      slug: "seis-apps-um-caderno",
      cat: "essay",
      date_pt: "17 Abr 2026", date_en: "Apr 17, 2026", iso: "2026-04-17",
      read: "8",
      tags: ["indie", "solo", "2026", "reflexão"], feat: true,
      img: { h: 20, h2: 45, pattern: "diag" },
      title_pt: "Seis apps, um caderno — por que parei de separar produto de conteúdo",
      title_en: "Six apps, one notebook — why I stopped separating product from writing",
      excerpt_pt: "Passei dois anos tratando blog e produto como coisas diferentes. Aqui está o que sobrou depois que joguei fora essa separação, e por que é a única coisa que me importa construir em 2026.",
      excerpt_en: "For two years I treated blog and product like different things. Here's what's left after I threw that separation out, and why it's the only thing I care about building in 2026.",
    },
    {
      slug: "um-cms-para-governar",
      cat: "code",
      date_pt: "14 Abr 2026", date_en: "Apr 14, 2026", iso: "2026-04-14",
      read: "6",
      tags: ["supabase", "nextjs", "arquitetura", "cms"],
      img: { h: 200, h2: 30, pattern: "grid" },
      title_pt: "Um CMS para governar todos — arquitetura de publicação cross-site",
      title_en: "One CMS to rule them all — cross-site publishing architecture",
      excerpt_pt: "A arquitetura por trás de publicar o mesmo post em seis sites diferentes sem copy-paste. Supabase, uma junction table, e uma caixa de checkbox que mudou meu fluxo.",
      excerpt_en: "The architecture behind publishing the same post to six different sites without copy-paste. Supabase, a junction table, and one checkbox that changed my workflow.",
    },
    {
      slug: "onboarding-que-nao-pede",
      cat: "product",
      date_pt: "10 Abr 2026", date_en: "Apr 10, 2026", iso: "2026-04-10",
      read: "5",
      tags: ["ux", "produto", "tonagarantia"],
      img: { h: 140, h2: 90, pattern: "dots" },
      title_pt: "Onboarding que não pede nada: de 7 telas pra 1",
      title_en: "Onboarding that asks for nothing: from 7 screens to 1",
      excerpt_pt: "Como reduzi o onboarding do TôNaGarantia em 86% — e por que isso importa mais do que qualquer feature nova que eu lance nos próximos seis meses.",
      excerpt_en: "How I cut TôNaGarantia's onboarding by 86% — and why that matters more than any feature I'll ship in the next six months.",
    },
    {
      slug: "semana-14-quase-desisti",
      cat: "diary",
      date_pt: "05 Abr 2026", date_en: "Apr 05, 2026", iso: "2026-04-05",
      read: "3",
      tags: ["diário", "solo", "tonagarantia"],
      img: { h: 280, h2: 250, pattern: "blur" },
      title_pt: "Semana 14: quase desisti",
      title_en: "Week 14: I almost gave up",
      excerpt_pt: "A semana em que o TNG quase foi pro lixo. E os sete dias depois que mudaram tudo.",
      excerpt_en: "The week TNG almost went in the trash. And the seven days after that changed everything.",
    },
    {
      slug: "custo-invisivel-contratar",
      cat: "career",
      date_pt: "28 Mar 2026", date_en: "Mar 28, 2026", iso: "2026-03-28",
      read: "4",
      tags: ["solo", "gestão", "dinheiro"],
      img: { h: 60, h2: 120, pattern: "stripe" },
      title_pt: "O custo invisível de contratar (quando você é um)",
      title_en: "The hidden cost of hiring (when you're just one person)",
      excerpt_pt: "Terceirizei duas features e paguei caro. Um post honesto sobre quando delegar faz sentido, quando não, e as três perguntas que eu faço antes.",
      excerpt_en: "I contracted out two features and paid for it. An honest post about when delegation works, when it doesn't, and the three questions I ask first.",
    },
    {
      slug: "supabase-next15-dois-anos",
      cat: "code",
      date_pt: "22 Mar 2026", date_en: "Mar 22, 2026", iso: "2026-03-22",
      read: "7",
      tags: ["supabase", "nextjs", "retrospectiva"],
      img: { h: 200, h2: 260, pattern: "diag" },
      title_pt: "Supabase + Next 15, dois anos depois: o que eu manteria, o que eu trocaria",
      title_en: "Supabase + Next 15, two years in: what I'd keep, what I'd swap",
      excerpt_pt: "O que eu ainda gosto, o que me irrita, e as três coisas que eu trocaria sem pensar duas vezes se começasse o TNG hoje.",
      excerpt_en: "What I still love, what bugs me, and the three things I'd swap without a second thought if I started TNG today.",
    },
    {
      slug: "cafezinho-deploy",
      cat: "diary",
      date_pt: "15 Mar 2026", date_en: "Mar 15, 2026", iso: "2026-03-15",
      read: "2",
      tags: ["diário", "deploy", "solo"],
      img: { h: 28, h2: 40, pattern: "dots" },
      title_pt: "O deploy da sexta-feira (e o cafezinho às 23h)",
      title_en: "Friday's deploy (and an 11pm coffee)",
      excerpt_pt: "Regra zero de solo builder: nunca faça deploy na sexta à noite. Regra um: às vezes a regra zero é uma mentira.",
      excerpt_en: "Solo builder rule zero: never deploy on a Friday night. Rule one: sometimes rule zero is a lie.",
    },
    {
      slug: "ferramentas-abril-2026",
      cat: "tools",
      date_pt: "08 Mar 2026", date_en: "Mar 08, 2026", iso: "2026-03-08",
      read: "5",
      tags: ["stack", "ferramentas", "solo"],
      img: { h: 32, h2: 60, pattern: "grid" },
      title_pt: "Ferramentas que eu uso em abril de 2026 (e as que deixei de usar)",
      title_en: "Tools I use in April 2026 (and the ones I dropped)",
      excerpt_pt: "Uma lista honesta: stack, apps, serviços pagos. Também: as três assinaturas que cancelei mês passado e não senti falta.",
      excerpt_en: "An honest list: stack, apps, paid services. Plus: three subscriptions I cancelled last month and didn't miss.",
    },
    {
      slug: "produto-sem-mercado",
      cat: "essay",
      date_pt: "01 Mar 2026", date_en: "Mar 01, 2026", iso: "2026-03-01",
      read: "6",
      tags: ["produto", "validação", "lição"],
      img: { h: 210, h2: 180, pattern: "blur" },
      title_pt: "Produto sem mercado é hobby. Mercado sem produto é discurso.",
      title_en: "Product without a market is a hobby. Market without a product is a pitch.",
      excerpt_pt: "Passei seis meses construindo algo que ninguém pediu. O que eu aprendi sobre validação — e sobre parar de ouvir gurus de Twitter.",
      excerpt_en: "I spent six months building something nobody asked for. What I learned about validation — and about tuning out Twitter gurus.",
    },
    {
      slug: "analytics-minimalista",
      cat: "product",
      date_pt: "22 Feb 2026", date_en: "Feb 22, 2026", iso: "2026-02-22",
      read: "4",
      tags: ["produto", "métricas", "minimalismo"],
      img: { h: 170, h2: 220, pattern: "stripe" },
      title_pt: "Analytics minimalista: 3 métricas, zero dashboards",
      title_en: "Minimalist analytics: 3 metrics, zero dashboards",
      excerpt_pt: "Parei de olhar Mixpanel. Agora olho três números uma vez por semana. Produtividade subiu. Felicidade também.",
      excerpt_en: "I stopped looking at Mixpanel. Now I check three numbers once a week. Productivity's up. So is happiness.",
    },
    {
      slug: "quando-escrever-codigo",
      cat: "career",
      date_pt: "15 Feb 2026", date_en: "Feb 15, 2026", iso: "2026-02-15",
      read: "5",
      tags: ["solo", "gestão", "reflexão"],
      img: { h: 50, h2: 80, pattern: "diag" },
      title_pt: "Quando escrever código é a pior coisa que você pode fazer",
      title_en: "When writing code is the worst thing you can do",
      excerpt_pt: "Dev indie tem um reflexo: abrir o editor. Geralmente é errado. Um post sobre os momentos em que escrever código te atrasa.",
      excerpt_en: "Indie devs have a reflex: open the editor. Usually it's wrong. A post about when writing code slows you down.",
    },
    {
      slug: "bilingual-seo",
      cat: "tools",
      date_pt: "08 Feb 2026", date_en: "Feb 08, 2026", iso: "2026-02-08",
      read: "6",
      tags: ["seo", "i18n", "stack"],
      img: { h: 160, h2: 40, pattern: "dots" },
      title_pt: "SEO bilíngue sem sofrer: como estruturei PT+EN no mesmo domínio",
      title_en: "Bilingual SEO without suffering: structuring PT+EN on one domain",
      excerpt_pt: "hreflang, rotas, tradução assistida por AI, e o erro que fiz nos primeiros dois meses e me custou tráfego orgânico.",
      excerpt_en: "hreflang, routing, AI-assisted translation, and the mistake I made in the first two months that cost me organic traffic.",
    },
    {
      slug: "roadmap-publico",
      cat: "essay",
      date_pt: "01 Feb 2026", date_en: "Feb 01, 2026", iso: "2026-02-01",
      read: "4",
      tags: ["indie", "gestão", "lição"],
      img: { h: 245, h2: 200, pattern: "grid" },
      title_pt: "Roadmap público: os prós, os contras, e por que eu voltei atrás",
      title_en: "Public roadmap: the pros, the cons, and why I rolled it back",
      excerpt_pt: "Abri meu roadmap pro público por três meses. Aqui está o que ganhei, o que perdi, e por que eu fechei de novo.",
      excerpt_en: "I made my roadmap public for three months. Here's what I gained, what I lost, and why I closed it again.",
    },
    {
      slug: "eu-escrevo-todo-dia",
      cat: "diary",
      date_pt: "25 Jan 2026", date_en: "Jan 25, 2026", iso: "2026-01-25",
      read: "3",
      tags: ["diário", "escrita", "hábitos"],
      img: { h: 0, h2: 30, pattern: "blur" },
      title_pt: "Eu escrevo todo dia há 400 dias. Aqui está o que mudou.",
      title_en: "I've written every day for 400 days. Here's what changed.",
      excerpt_pt: "Não é sobre disciplina. É sobre perder o medo da página em branco — e o que acontece quando isso acontece.",
      excerpt_en: "It's not about discipline. It's about losing fear of the blank page — and what happens once you do.",
    },
  ],

  // YouTube videos — enriched for pinboard
  videos: [
    {
      id: "v1", duration: "14:32",
      tags: ["live", "cms", "supabase", "nextjs"], iso: "2026-04-15",
      series_pt: "Build in public", series_en: "Build in public",
      title_pt: "Construindo um CMS multi-site do zero (live coding)",
      title_en: "Building a multi-site CMS from scratch (live coding)",
      desc_pt: "Três horas de live em 14 min: arquitetura, schema e o primeiro deploy.",
      desc_en: "Three hours of live-coding cut to 14 min: architecture, schema, first deploy.",
      views_pt: "8.2k visualizações", views_en: "8.2k views",
      date_pt: "há 3 dias", date_en: "3 days ago",
      thumb: { h: 18, h2: 200 },
      feat: true,
    },
    {
      id: "v2", duration: "22:08",
      tags: ["setup", "nextjs", "arquitetura"], iso: "2026-04-09",
      series_pt: "Dev setup", series_en: "Dev setup",
      title_pt: "Como eu estruturo um app Next 15 em produção",
      title_en: "How I structure a Next 15 app in production",
      desc_pt: "Pastas, rotas, server actions, e o erro que me custou duas semanas.",
      desc_en: "Folders, routes, server actions, and the mistake that cost me two weeks.",
      views_pt: "12k visualizações", views_en: "12k views",
      date_pt: "há 1 semana", date_en: "1 week ago",
      thumb: { h: 110, h2: 180 },
    },
    {
      id: "v3", duration: "09:47",
      tags: ["setup", "home-office"], iso: "2026-04-02",
      series_pt: "Oficina", series_en: "Workshop",
      title_pt: "Tour pelo meu setup (home office em BH)",
      title_en: "Tour of my setup (home office in Brazil)",
      desc_pt: "O cantinho onde tudo acontece. Sem Amazon links, prometo.",
      desc_en: "The corner where everything happens. No Amazon links, promise.",
      views_pt: "31k visualizações", views_en: "31k views",
      date_pt: "há 2 semanas", date_en: "2 weeks ago",
      thumb: { h: 35, h2: 60 },
    },
    {
      id: "v4", duration: "17:20",
      tags: ["bugs", "retrospectiva"], iso: "2026-03-25",
      series_pt: "Diário de bugs", series_en: "Bug diary",
      title_pt: "Três bugs que me custaram um final de semana",
      title_en: "Three bugs that cost me a weekend",
      desc_pt: "Timezone, race condition, e um console.log esquecido em produção.",
      desc_en: "Timezone, race condition, and a console.log left in production.",
      views_pt: "5.4k visualizações", views_en: "5.4k views",
      date_pt: "há 3 semanas", date_en: "3 weeks ago",
      thumb: { h: 220, h2: 290 },
    },
  ],

  // Channels — one per locale (different content in each)
  channels: [
    {
      locale: "pt",
      name: "@bythiagofigueiredo",
      lang_label_pt: "em português", lang_label_en: "in Portuguese",
      flag: "🇧🇷",
      subs_pt: "4,2k inscritos", subs_en: "4.2k subscribers",
      videos_pt: "48 vídeos",    videos_en: "48 videos",
      schedule_pt: "novo vídeo toda quinta", schedule_en: "new video every Thursday",
      url: "https://youtube.com/@bythiagofigueiredo",
    },
    {
      locale: "en",
      name: "@thiagofigueiredo",
      lang_label_pt: "em inglês",  lang_label_en: "in English",
      flag: "🇺🇸",
      subs_pt: "1,8k inscritos", subs_en: "1.8k subscribers",
      videos_pt: "22 vídeos",    videos_en: "22 videos",
      schedule_pt: "novo vídeo a cada 2 semanas", schedule_en: "new video every 2 weeks",
      url: "https://youtube.com/@thiagofigueiredo",
    },
  ],

  // External sites (outbound navigation)
  sites: {
    dev: { label_pt: "Site dev", label_en: "Dev site", url: "https://dev.bythiagofigueiredo.com" },
    contact: { label_pt: "Contato", label_en: "Contact", url: "/contact" },
  },

  // Newsletters (plural — user subscribes to any combination).
  // First item (id: "main") is the primary one, pre-checked by default.
  newsletters: [
    {
      id: "main",
      slug_pt: "diario-do-bythiago",
      slug_en: "the-bythiago-diary",
      primary: true,
      color: "#C14513",
      color_dark: "#FF8240",
      badge_pt: "principal", badge_en: "main",
      name_pt: "Diário do bythiago",
      name_en: "The bythiago diary",
      tagline_pt: "o resumo da semana — blog + canal + o que andei pensando.",
      tagline_en: "the week in review — blog + channel + what I've been thinking.",
      cadence_pt: "1× por semana, sextas",
      cadence_en: "weekly, Fridays",
      sample_pt: "semana 17 · CMS + um bug que me custou três horas",
      sample_en: "week 17 · CMS + a bug that cost me three hours",
      subs_count: 1240,
      issues_count: 34,
      subs_pt: "1.240 inscritos",
      subs_en: "1,240 subscribers",
      issues_pt: "34 edições",
      issues_en: "34 issues",
      description_pt: "Toda sexta, eu paro e escrevo o que aconteceu na semana — o post novo do blog, o vídeo do canal, o bug que me derrubou, o livro que tô lendo. É a newsletter principal, a que junta tudo num lugar só. Não é resumo formal: é mais carta pra um amigo que tá longe.",
      description_en: "Every Friday, I stop and write down the week — the new blog post, the new video, the bug that took me down, the book I'm reading. It's the main newsletter, the one that pulls everything together. Not a corporate digest: more like a letter to a friend who's far away.",
      promise_pt: [
        "o post mais recente, com nota pessoal de bastidor",
        "o vídeo da semana, com o que eu cortei e por quê",
        "3–5 links que eu salvei pra ler depois",
        "uma coisa pequena que aprendi (ou quebrei)",
      ],
      promise_en: [
        "the latest post, with a behind-the-scenes note",
        "the week's video, with what I cut and why",
        "3–5 links I bookmarked to read later",
        "one small thing I learned (or broke)",
      ],
      sample_issues_pt: [
        { num: 17, date: "sex 26 abr", subject: "semana 17 · CMS + um bug que me custou três horas", preview: "Essa semana foi de duas frentes: terminei a refatoração do CMS (finalmente!) e levei três horas pra entender por que um cron de meia-noite estava rodando às 23h59. Spoiler: timezone no banco." },
        { num: 16, date: "sex 19 abr", subject: "semana 16 · três links e um pedido pra você", preview: "Sem post novo dessa vez — tô escrevendo um longo sobre tipos de banco, vai sair semana que vem. No lugar, três links que me marcaram, e um pedido pra quem responder esse email." },
        { num: 15, date: "sex 12 abr", subject: "semana 15 · voltei pro Postgres, escrevi um post", preview: "Decidi voltar pro Postgres depois de quatro meses brincando com SQLite. O post saiu hoje, e é mais uma confissão do que um tutorial. Spoiler do final: a versão simples ganhou." },
      ],
      sample_issues_en: [
        { num: 17, date: "Fri Apr 26", subject: "week 17 · CMS + a bug that cost me three hours", preview: "Two fronts this week: finally finished the CMS refactor and spent three hours figuring out why a midnight cron was running at 23:59. Spoiler: timezone in the DB." },
        { num: 16, date: "Fri Apr 19", subject: "week 16 · three links and one favor", preview: "No new post this time — I'm writing a long one about database types, ships next week. Instead, three links that hit me, and one favor for anyone who replies to this email." },
        { num: 15, date: "Fri Apr 12", subject: "week 15 · went back to Postgres, wrote a post", preview: "Decided to go back to Postgres after four months playing with SQLite. The post went up today, and it's more confession than tutorial. Spoiler: the simple version won." },
      ],
      testimonial_pt: { who: "Marina P.", text: "é a única newsletter que eu abro na sexta sem ter que prometer pra mim mesma 'depois eu leio'." },
      testimonial_en: { who: "Marina P.", text: "the only newsletter I open on Friday without telling myself 'I'll read it later'." },
    },
    {
      id: "trips",
      slug_pt: "curvas-e-estradas",
      slug_en: "curves-and-roads",
      color: "#2C6E49",
      color_dark: "#5FA87D",
      badge_pt: "novo", badge_en: "new",
      name_pt: "Curvas & estradas",
      name_en: "Curves & roads",
      tagline_pt: "relatos de moto, mapas, comida de beira de estrada.",
      tagline_en: "motorcycle trips, maps, roadside food.",
      cadence_pt: "quando eu pegar estrada",
      cadence_en: "whenever I hit the road",
      sample_pt: "serra da canastra · 3 dias, dois tanques, uma chuva",
      sample_en: "serra da canastra · 3 days, two tanks, one storm",
      subs_count: 182,
      issues_count: 4,
      subs_pt: "182 inscritos",
      subs_en: "182 subscribers",
      issues_pt: "4 edições",
      issues_en: "4 issues",
      description_pt: "Eu tenho uma Tenere 250 e uma certeza: a melhor parte do trabalho de hoje é poder fechar o laptop na quinta e abrir o mapa. Essa newsletter é o que sobra depois da viagem — o trecho que valeu, o que evitar, o restaurante de beira de estrada que não tem Google review, e a foto que a câmera do celular conseguiu salvar.",
      description_en: "I have a Tenere 250 and one certainty: the best part of today's work is being able to close the laptop on Thursday and open the map. This newsletter is what's left after the trip — the stretch that was worth it, what to avoid, the roadside diner with no Google reviews, and the photo my phone camera managed to save.",
      promise_pt: [
        "o trajeto, com mapa anotado",
        "3–5 lugares pra parar (e 1 pra evitar)",
        "foto crua, sem filtro, sem stories",
        "o que deu errado — porque sempre dá",
      ],
      promise_en: [
        "the route, with an annotated map",
        "3–5 places to stop (and 1 to avoid)",
        "raw photos, no filter, no stories",
        "what went wrong — because it always does",
      ],
      sample_issues_pt: [
        { num: 4, date: "sex 22 mar", subject: "serra da canastra · 3 dias, dois tanques, uma chuva", preview: "Saí de BH na quinta de manhã, dormi em São Roque de Minas, e voltei segunda derretido. O mapa anotado está no fim do email. A feijoada do bar do Zé Pião continua valendo cada metro." },
        { num: 3, date: "sex 16 fev", subject: "diamantina ida & volta · o que cabe no top case", preview: "Lista crua do que sobrou útil depois de mil kilômetros: capa de chuva, multiferramenta, e um par de meias extra. Tudo o resto eu carreguei à toa." },
        { num: 2, date: "sex 15 dez", subject: "chapada · o restaurante que mudou a viagem", preview: "Era pra ser parada rápida e virou tarde inteira. Anotei o nome, o telefone do dono, e por que você precisa parar antes do pôr do sol — motivo é mais bonito que prático." },
      ],
      sample_issues_en: [
        { num: 4, date: "Fri Mar 22", subject: "serra da canastra · 3 days, two tanks, one storm", preview: "Left Belo Horizonte Thursday morning, slept in São Roque de Minas, came back Monday melted. The annotated map is at the end of the email. The feijoada at Zé Pião's bar is still worth every meter." },
        { num: 3, date: "Fri Feb 16", subject: "diamantina round-trip · what fits in the top case", preview: "Raw list of what was actually useful after a thousand kilometers: rain jacket, multi-tool, and one extra pair of socks. Everything else I hauled for nothing." },
        { num: 2, date: "Fri Dec 15", subject: "chapada · the restaurant that saved the trip", preview: "Supposed to be a quick stop, became the whole afternoon. I wrote down the name, the owner's phone, and why you need to stop before sunset — the reason is more beautiful than practical." },
      ],
      testimonial_pt: { who: "Rafael S.", text: "li o de canastra e fui no fim de semana seguinte. parei nos mesmos lugares. a feijoada estava lá, igualzinha." },
      testimonial_en: { who: "Rafael S.", text: "I read the canastra one and went the next weekend. stopped at the same places. the beans were there, just like he said." },
    },
    {
      id: "growth",
      slug_pt: "crescer-de-dentro",
      slug_en: "grow-inward",
      color: "#6B4A91",
      color_dark: "#A983D6",
      name_pt: "Crescer de dentro",
      name_en: "Grow inward",
      tagline_pt: "hábitos, leituras, o que me ajudou a não surtar.",
      tagline_en: "habits, books, what's kept me from losing it.",
      cadence_pt: "a cada 2 semanas, domingos",
      cadence_en: "every 2 weeks, Sundays",
      sample_pt: "o que mudou quando parei de medir produtividade",
      sample_en: "what changed when I stopped measuring productivity",
      subs_count: 408,
      issues_count: 11,
      subs_pt: "408 inscritos",
      subs_en: "408 subscribers",
      issues_pt: "11 edições",
      issues_en: "11 issues",
      description_pt: "Eu trabalho sozinho. Isso significa que ninguém me empurra, ninguém me cobra, e ninguém me lembra de almoçar. Essa newsletter é o que eu fui aprendendo a fazer pra continuar funcional — não é guru de produtividade, é mais o caderno de campo de quem tá testando o que dá certo no longo prazo. Domingo, café, e uma pergunta pra semana.",
      description_en: "I work alone. That means nobody pushes me, nobody nags me, and nobody reminds me to have lunch. This newsletter is what I've been learning to do to stay functional — not productivity-guru stuff, more like the field journal of someone testing what works long-term. Sunday, coffee, and one question for the week.",
      promise_pt: [
        "um hábito que eu testei (e o que aconteceu)",
        "um livro ou ensaio que mexeu comigo",
        "uma pergunta pra você levar na semana",
        "sem checklist, sem app novo, sem urgência",
      ],
      promise_en: [
        "a habit I tested (and what happened)",
        "a book or essay that hit me",
        "a question for you to carry through the week",
        "no checklist, no new app, no urgency",
      ],
      sample_issues_pt: [
        { num: 11, date: "dom 21 abr", subject: "o que mudou quando parei de medir produtividade", preview: "Passei seis meses anotando hora trabalhada, tópicos cobertos, peso semanal. Parei em março. Essa edição é sobre o que ficou melhor (mais), o que ficou pior (uma coisa), e a pergunta pra você levar." },
        { num: 10, date: "dom 7 abr", subject: "o ritual de domingo · 4 anos depois", preview: "Começou simples: café, caderno, 30 minutos de silêncio. Quatro anos depois, está quase igual — mas com três pequenas mudanças que valem ouro. Conto cada uma e por quê." },
        { num: 9, date: "dom 24 mar", subject: "sobre não saber o que você quer (e tudo bem)", preview: "A gente romantiza propósito. Mas a maior parte do tempo eu não sei o que quero, e isso virou ferramenta. Edição curta, com livro indicado e uma pergunta direta." },
      ],
      sample_issues_en: [
        { num: 11, date: "Sun Apr 21", subject: "what changed when I stopped measuring productivity", preview: "I spent six months tracking hours worked, topics covered, weekly weight. I stopped in March. This issue is about what got better (most things), what got worse (one thing), and the question for you to carry." },
        { num: 10, date: "Sun Apr 7", subject: "the Sunday ritual · 4 years in", preview: "Started simple: coffee, notebook, 30 minutes of silence. Four years in, it's almost the same — but with three small changes that are worth gold. I tell each one and why." },
        { num: 9, date: "Sun Mar 24", subject: "on not knowing what you want (and that being fine)", preview: "We romanticize purpose. But most of the time I don't know what I want, and that became a tool. Short issue, with a book recommendation and one direct question." },
      ],
      testimonial_pt: { who: "Camila T.", text: "é a única coisa de produtividade que eu não cancelei. ele não vende. ele só conta o que tá funcionando." },
      testimonial_en: { who: "Camila T.", text: "the only productivity thing I haven't unsubscribed from. he doesn't sell. he just shares what's working." },
    },
    {
      id: "code",
      slug_pt: "codigo-em-portugues",
      slug_en: "code-in-portuguese",
      color: "#1F5F8B",
      color_dark: "#5FA8E0",
      name_pt: "Código em português",
      name_en: "Code in Portuguese",
      tagline_pt: "decisões de stack, bugs reais, sem hype.",
      tagline_en: "stack decisions, real bugs, no hype.",
      cadence_pt: "mensal, última quinta",
      cadence_en: "monthly, last Thursday",
      sample_pt: "por que voltei pro Postgres (e parei de tentar ser inteligente)",
      sample_en: "why I went back to Postgres (and stopped trying to be clever)",
      subs_count: 620,
      issues_count: 8,
      subs_pt: "620 inscritos",
      subs_en: "620 subscribers",
      issues_pt: "8 edições",
      issues_en: "8 issues",
      description_pt: "A internet técnica em inglês é boa demais. Mas falta uma coisa em português que não seja tutorial básico nem tradução tardia de hype. Essa newsletter é o que eu queria ter lido quando estava decidindo se aguentava migrar pra microserviço (não aguentei) ou se compensava trocar de banco (não compensava). Decisões reais, com nome e número do projeto.",
      description_en: "Technical writing in English is great. But there's a gap in Portuguese — between basic tutorials and late translations of hype. This newsletter is what I wish I'd read when deciding whether microservices were worth it (they weren't) or whether to switch databases (it wasn't). Real decisions, with project names and numbers.",
      promise_pt: [
        "uma decisão real de stack (e por que)",
        "o bug do mês — diagnóstico completo",
        "código que rodou em produção",
        "zero hype, zero 'X tools every dev needs'",
      ],
      promise_en: [
        "a real stack decision (and why)",
        "the bug of the month — full postmortem",
        "code that ran in production",
        "zero hype, zero 'X tools every dev needs'",
      ],
      sample_issues_pt: [
        { num: 8, date: "qui 25 abr", subject: "por que voltei pro Postgres (e parei de tentar ser inteligente)", preview: "Quatro meses no SQLite, dois pinos no pé, e a lição de sempre: simples ganha. Código de migração no fim, com os dois bugs que me custaram caro — e o que eu manteria do SQLite." },
        { num: 7, date: "qui 28 mar", subject: "o bug que só aparecia no fuso horário do Acre", preview: "Postmortem completo: ticket, log, hipóteses descartadas, fix. O bug nasceu de uma decisão boba de 2024 e só apareceu agora porque um inscrito mandou email às 23h57 do horário dele." },
        { num: 6, date: "qui 29 fev", subject: "6 apps, 1 schema · como eu compartilho banco", preview: "As seis aplicações do meu monorepo dividem o mesmo Postgres. Mostro o schema, as três regras que respeito, e onde quase me dei mal — com diff de migration completo." },
      ],
      sample_issues_en: [
        { num: 8, date: "Thu Apr 25", subject: "why I went back to Postgres (and stopped trying to be clever)", preview: "Four months on SQLite, two pins in the foot, and the usual lesson: simple wins. Migration code at the end, with the two bugs that cost me dearly — and what I'd keep from SQLite." },
        { num: 7, date: "Thu Mar 28", subject: "the bug that only appeared in the Acre timezone", preview: "Full postmortem: ticket, log, discarded hypotheses, fix. The bug was born from a silly 2024 decision and only surfaced now because a subscriber emailed at 23:57 their time." },
        { num: 6, date: "Thu Feb 29", subject: "6 apps, 1 schema · how I share a database", preview: "The six apps in my monorepo share the same Postgres. I show the schema, the three rules I follow, and where I almost screwed myself — with full migration diff." },
      ],
      testimonial_pt: { who: "Diogo M.", text: "finalmente alguém escreve em português sem fingir que é o McKinsey do dev. eu encaminho pra galera do time." },
      testimonial_en: { who: "Diogo M.", text: "finally someone writes in Portuguese without pretending to be the McKinsey of dev. I forward it to my team." },
    },
  ],

  // Author (single author for v1 — structure supports guests later)
  author: {
    id: "thiago",
    slug: "thiago",
    name: "Thiago Figueiredo",
    avatar_initials: "TF",
    role_pt: "Dev indie, BH",
    role_en: "Indie dev, Brazil",
    bio_pt: "Construo software há seis anos. Desde 2024, só pra mim mesmo: seis apps no forno, um canal no YouTube, um blog que virou o centro de tudo. Aqui você me acha escrevendo uma vez por semana, filmando uma vez por semana, e quebrando coisa em produção com a frequência que Deus achar justa.",
    bio_en: "I've built software for six years. Since 2024, only for myself: six apps cooking, a YouTube channel, a blog that became the center of everything. Here you'll find me writing once a week, filming once a week, and breaking things in production with whatever frequency God finds fair.",
    social: [
      { platform: "youtube", url: "https://youtube.com/@bythiagofigueiredo", label: "YouTube" },
      { platform: "github",  url: "https://github.com/tnfigueiredo",          label: "GitHub" },
      { platform: "x",       url: "https://x.com/bythiagofig",                label: "X" },
      { platform: "rss",     url: "/rss.xml",                                  label: "RSS" },
    ],
  },

  // Rich post body content — keyed by slug. Each entry is an array of blocks.
  // Block types: h2, h3, p, quote, list, code, figure, callout, note
  postBodies: {
    "manifesto-bythiagofigueiredo": {
      footnotes: {
        pt: [
          "A junction table tem três colunas: <code>post_id</code>, <code>destination_id</code>, <code>rendered_at</code>. Isso é suficiente pra saber pra onde cada post foi e quando. O resto é template por destino.",
          "Ryan Holiday chama isso de \"Finished is better than perfect\". Eu descobri do jeito difícil: o melhor texto da minha vida morreu na pasta <code>drafts/</code> porque eu queria \"só mais uma revisão\". Três anos depois ainda está lá.",
          "Isso inclui aceitar patrocínio. Se eu aceitar grana pra publicar algo, vira um produto. Se vira um produto, tem cliente. Se tem cliente, tem stakeholder. Se tem stakeholder, acabou o caderno.",
        ],
        en: [
          "The junction table has three columns: <code>post_id</code>, <code>destination_id</code>, <code>rendered_at</code>. That's enough to know where each post went and when. The rest is per-destination templating.",
          "Ryan Holiday calls this \"Finished is better than perfect\". I learned the hard way: the best piece I ever wrote died in <code>drafts/</code> because I wanted \"just one more revision\". Three years later, still there.",
          "That includes taking sponsorships. If I take money to publish something, it becomes a product. If it's a product, it has customers. If it has customers, it has stakeholders. If it has stakeholders, the notebook is over.",
        ],
      },
      pt: [
        { type: "p", text: "Eu tenho seis apps em produção, um canal de YouTube bilíngue, uma newsletter que saiu de 40 para 1.400 leitores em um ano, e uma pasta chamada <code>drafts/</code> com 83 arquivos <code>.md</code> que nunca viram a luz do dia. Tudo isso vivia espalhado. Este site é o lugar onde eu junto." },
        { type: "p", text: "Mas antes de explicar o que é — deixa eu explicar o que <em>não</em> é. Porque é o <em>não</em> que me manteve longe de fazer isso por três anos." },
        { type: "h2", id: "o-que-nao-e", text_pt: "O que não é", text_en: "What it isn't" },
        { type: "p", text: "Isto não é um portfólio. Portfólio é um museu — você visita, aplaude educadamente, vai embora. Eu não quero um museu. Eu quero um caderno aberto em cima da mesa, com café derramado no canto e anotações na margem." },
        { type: "p", text: "Também não é um feed. Feed é algoritmo — ele decide o que você lê. Aqui você decide. A ordem é cronológica. A curadoria é minha. A leitura é sua." },
        { type: "p", text: "E não é um blog corporativo. Não vou escrever \"5 dicas para você aumentar sua produtividade em 2026\". Vou escrever \"semana 14: quase desisti\". Se isso não te ajuda — e pode não ajudar — pelo menos vai ser verdade." },
        { type: "quote", text: "Um caderno aberto é pior que um portfólio, mas honesto. Eu prefiro honesto." },
        { type: "h2", id: "o-que-e", text_pt: "O que é, então", text_en: "What it is, then" },
        { type: "p", text: "É um hub. Um ponto central que concentra três coisas que antes viviam em pastas separadas na minha cabeça:" },
        { type: "list", items: [
          "<b>Escritos</b> — posts, ensaios, relatos. Português e inglês, mesma cabeça.",
          "<b>Vídeos</b> — o que eu filmo pro canal, com link e resumo.",
          "<b>Newsletters</b> — quatro cartas diferentes, você assina as que interessam.",
        ]},
        { type: "p", text: "Tudo isso puxa do mesmo CMS. Um post meu vai pro blog, pro feed da newsletter, pro YouTube description, e pro campaign landing se eu quiser — com <em>um clique</em>. Isso é o que me fez parar de procrastinar e finalmente construir." },
        { type: "h3", id: "o-cms", text_pt: "Um parêntese sobre o CMS", text_en: "An aside about the CMS" },
        { type: "p", text: "Eu gastei três meses construindo o mecanismo antes de pensar no design. Isso é coisa de dev — errado, provavelmente, mas foi o que fez sentido. A ideia é simples: em vez de publicar seis vezes, publico uma. O mesmo conteúdo vira seis coisas diferentes dependendo do destino." },
        { type: "code", lang: "ts", text: "// Publicar uma vez, distribuir para onde importa\nawait publish(post, {\n  sites: [\"bythiago\", \"dev.bythiago\", \"tng-blog\"],\n  as: {\n    newsletter: \"main\",\n    campaign: null,\n    youtube: { includeDescription: true },\n  },\n})" },
        { type: "p", text: "Isso não é mágica. É uma junction table no Supabase e uma caixa de checkbox<sup class=\"fn\" data-fn=\"1\" id=\"ref-1\">1</sup>. Mas é o que me permitiu parar de copiar e colar." },
        { type: "h2", id: "as-tres-promessas", text_pt: "As três promessas", text_en: "The three promises" },
        { type: "p", text: "Eu prometi a mim mesmo três coisas quando abri este caderno. Estou colocando elas aqui em público pra que você cobre — e pra que eu não esqueça quando cansar." },
        { type: "h3", id: "promessa-1", text_pt: "1. Escrever mesmo quando for ruim", text_en: "1. Write even when it's bad" },
        { type: "p", text: "Dos 83 drafts na pasta, uns 60 são ruins. O erro foi pensar que eu podia decidir antes de escrever se eles seriam bons<sup class=\"fn\" data-fn=\"2\" id=\"ref-2\">2</sup>. Você só sabe escrevendo. Então a promessa é: termina. Publica. Se não prestar, apaga depois. Mas termina." },
        { type: "h3", id: "promessa-2", text_pt: "2. Nunca rodar anúncio que eu não usaria", text_en: "2. Never run an ad I wouldn't use myself" },
        { type: "p", text: "Vai ter publicidade neste site — Google Ads porque blog precisa pagar servidor, e autopromoção dos meus próprios projetos. Mas eu prometi que nunca vou rodar anúncio de terceiro que eu mesmo não usaria. Sem affiliate link de curso que eu não fiz. Sem banner de produto que eu não testei." },
        { type: "h3", id: "promessa-3", text_pt: "3. Não transformar em startup", text_en: "3. Don't turn it into a startup" },
        { type: "p", text: "Este lugar é um caderno, não um produto. Não vai ter CEO. Não vai ter series A. Não vai virar uma holding<sup class=\"fn\" data-fn=\"3\" id=\"ref-3\">3</sup>. Quando eu cansar — e eu vou cansar — eu paro de publicar, deixo o arquivo no ar, e vou fazer outra coisa. Esse é o acordo comigo mesmo." },
        { type: "callout", text: "Se você achar este site daqui a cinco anos e a última publicação for de 2028, é porque eu estava cansado e fui fazer outra coisa. Tá tudo bem. O arquivo fica." },
        { type: "h2", id: "como-navegar", text_pt: "Como navegar", text_en: "How to get around" },
        { type: "p", text: "Se você é dev, vai curtir a categoria <b>Código</b>. Se você gosta de diário, o <b>Diário</b> é onde moram os textos curtos e pessoais. <b>Ensaios</b> é onde eu me demoro em um assunto. <b>Produto</b> e <b>Ferramentas</b> são pra quem quer saber como eu construo e com o quê." },
        { type: "p", text: "A <a href=\"#newsletter\">newsletter</a> é o melhor jeito de não perder nada. Quatro cartas diferentes — você escolhe quais assinar. Sem spam, cancelar é um clique." },
        { type: "p", text: "E se você caiu aqui por acaso — oi. Fica. Lê o que te chamar atenção. Vai embora. Volta quando quiser. É isso." },
      ],
      en: [
        { type: "p", text: "I have six apps in production, a bilingual YouTube channel, a newsletter that grew from 40 to 1,400 readers in a year, and a folder called <code>drafts/</code> with 83 <code>.md</code> files that never saw daylight. All of it lived scattered. This site is the place where I pull it together." },
        { type: "p", text: "But before I explain what it is — let me explain what it <em>isn't</em>. Because it's the <em>isn't</em> that kept me from doing this for three years." },
        { type: "h2", id: "o-que-nao-e", text_pt: "O que não é", text_en: "What it isn't" },
        { type: "p", text: "This isn't a portfolio. A portfolio is a museum — you visit, clap politely, leave. I don't want a museum. I want a notebook open on the desk, with coffee spilled in the corner and notes in the margin." },
        { type: "p", text: "It also isn't a feed. A feed is an algorithm — it decides what you read. Here you decide. The order is chronological. The curation is mine. The reading is yours." },
        { type: "p", text: "And it isn't a corporate blog. I won't write \"5 tips to boost your productivity in 2026\". I'll write \"week 14: I almost gave up\". If it doesn't help you — and it might not — at least it'll be true." },
        { type: "quote", text: "An open notebook is worse than a portfolio, but honest. I'll take honest." },
        { type: "h2", id: "o-que-e", text_pt: "O que é, então", text_en: "What it is, then" },
        { type: "p", text: "It's a hub. A central place that pulls together three things that used to live in separate folders in my head:" },
        { type: "list", items: [
          "<b>Writing</b> — posts, essays, journal entries. Portuguese and English, same head.",
          "<b>Videos</b> — what I film for the channel, with a link and a summary.",
          "<b>Newsletters</b> — four different letters, you pick the ones you want.",
        ]},
        { type: "p", text: "All of it pulls from the same CMS. One post of mine goes to the blog, to the newsletter, to the YouTube description, and to a campaign landing if I want — with <em>one click</em>. That's what made me stop procrastinating and finally ship." },
        { type: "h3", id: "o-cms", text_pt: "Um parêntese sobre o CMS", text_en: "An aside about the CMS" },
        { type: "p", text: "I spent three months building the engine before thinking about the design. That's a dev thing — wrong, probably, but it's what made sense. The idea is simple: instead of publishing six times, I publish once. The same content becomes six different things depending on where it's going." },
        { type: "code", lang: "ts", text: "// Publish once, distribute where it matters\nawait publish(post, {\n  sites: [\"bythiago\", \"dev.bythiago\", \"tng-blog\"],\n  as: {\n    newsletter: \"main\",\n    campaign: null,\n    youtube: { includeDescription: true },\n  },\n})" },
        { type: "p", text: "This isn't magic. It's a junction table in Supabase and a checkbox<sup class=\"fn\" data-fn=\"1\" id=\"ref-1\">1</sup>. But it's what let me stop copy-pasting." },
        { type: "h2", id: "as-tres-promessas", text_pt: "As três promessas", text_en: "The three promises" },
        { type: "p", text: "I promised myself three things when I opened this notebook. I'm putting them here in public so you can hold me accountable — and so I don't forget when I get tired." },
        { type: "h3", id: "promessa-1", text_pt: "1. Escrever mesmo quando for ruim", text_en: "1. Write even when it's bad" },
        { type: "p", text: "Of the 83 drafts in the folder, about 60 are bad. The mistake was thinking I could decide before writing whether they'd be good<sup class=\"fn\" data-fn=\"2\" id=\"ref-2\">2</sup>. You only find out by writing. So the promise is: finish it. Publish it. If it doesn't hold up, delete it later. But finish." },
        { type: "h3", id: "promessa-2", text_pt: "2. Nunca rodar anúncio que eu não usaria", text_en: "2. Never run an ad I wouldn't use myself" },
        { type: "p", text: "There will be advertising on this site — Google Ads because a blog has to pay its server, and self-promotion of my own projects. But I promised I'd never run a third-party ad for something I wouldn't use myself. No affiliate links for courses I haven't taken. No banner ads for products I haven't tried." },
        { type: "h3", id: "promessa-3", text_pt: "3. Não transformar em startup", text_en: "3. Don't turn it into a startup" },
        { type: "p", text: "This place is a notebook, not a product. There won't be a CEO. There won't be a Series A. It won't become a holding company<sup class=\"fn\" data-fn=\"3\" id=\"ref-3\">3</sup>. When I get tired — and I will get tired — I stop publishing, leave the archive up, and go do something else. That's the deal with myself." },
        { type: "callout", text: "If you find this site five years from now and the last post is from 2028, it's because I got tired and went to do something else. That's okay. The archive stays." },
        { type: "h2", id: "como-navegar", text_pt: "Como navegar", text_en: "How to get around" },
        { type: "p", text: "If you're a dev, you'll like the <b>Code</b> category. If you like journal stuff, <b>Journal</b> is where the short, personal pieces live. <b>Essays</b> is where I take my time on something. <b>Product</b> and <b>Tools</b> are for people who want to know how I build and with what." },
        { type: "p", text: "The <a href=\"#newsletter\">newsletter</a> is the best way not to miss anything. Four different letters — pick the ones that interest you. No spam, unsubscribe is one click." },
        { type: "p", text: "And if you landed here by accident — hi. Stay. Read whatever catches your eye. Leave. Come back whenever. That's it." },
      ],
    },
  },

  // Mock comments for the meta post
  commentsMock: [
    {
      id: "c1", author: "Paula Reis", avatar_initials: "PR",
      date_pt: "há 2 dias", date_en: "2 days ago",
      text_pt: "A promessa #3 é a mais honesta que eu li em muito tempo. Guardei aqui.",
      text_en: "Promise #3 is the most honest thing I've read in a long time. Saved this one.",
      likes: 12,
      replies: [
        {
          id: "c1r1", author: "Thiago Figueiredo", avatar_initials: "TF", isAuthor: true,
          date_pt: "há 2 dias", date_en: "2 days ago",
          text_pt: "Obrigado, Paula. Escrever essa parte foi a que mais travou — a gente sempre quer fingir que a coisa vai durar pra sempre.",
          text_en: "Thanks, Paula. Writing that part was the hardest — we always want to pretend things will last forever.",
          likes: 7,
        },
      ],
    },
    {
      id: "c2", author: "Rafa Oliveira", avatar_initials: "RO",
      date_pt: "há 3 dias", date_en: "3 days ago",
      text_pt: "Esperando o post sobre como funciona a junction table no detalhe. Tem link?",
      text_en: "Waiting for a detailed post on how that junction table actually works. Got a link?",
      likes: 8,
      replies: [
        {
          id: "c2r1", author: "Thiago Figueiredo", avatar_initials: "TF", isAuthor: true,
          date_pt: "há 3 dias", date_en: "3 days ago",
          text_pt: "Próxima edição do Caderno de Campo tem o schema inteiro. Se quiser ficar sabendo, assina ali no rodapé.",
          text_en: "Next Field Notes issue has the full schema. If you want to catch it, subscribe down at the footer.",
          likes: 4,
        },
        {
          id: "c2r2", author: "Diego Souza", avatar_initials: "DS",
          date_pt: "há 2 dias", date_en: "2 days ago",
          text_pt: "+1, também curti o uso do rendered_at pra cache invalidation.",
          text_en: "+1, also liked the use of rendered_at for cache invalidation.",
          likes: 2,
        },
      ],
    },
    {
      id: "c3", author: "Carla Menezes", avatar_initials: "CM",
      date_pt: "há 5 dias", date_en: "5 days ago",
      text_pt: "Fiz minha própria versão disso ano passado e abandonei — seu CMS é mais simples que o meu, provavelmente é por isso que sobreviveu.",
      text_en: "I built my own version of this last year and dropped it — your CMS is simpler than mine, probably why yours survived.",
      likes: 5,
      replies: [],
    },
  ],

  // Section labels & UI strings
  ui: {
    pt: {
      brand_short: "bythiagofigueiredo",
      brand_tagline: "Escrito, codado e publicado em BH — por Thiago Figueiredo.",
      nav: {
        home: "Início",
        writing: "Escritos",
        categories: "Categorias",
        videos: "Vídeos",
        about: "Sobre",
        contact: "Contato",
        newsletter: "Newsletter",
        dev: "Site dev",
      },
      hero: {
        kicker: "Em destaque",
        read_cta: "Ler texto",
      },
      latest: {
        title: "Últimos textos",
        subtitle: "Tudo que eu escrevi nas últimas semanas, do mais novo pro mais antigo.",
        all_cta: "Ver todos os textos →",
      },
      most_read: "Mais lidos",
      most_read_sub: "Últimos 30 dias",
      videos: {
        kicker: "Vídeos",
        title: "Últimos vídeos do canal",
        cta: "Ver canal no YouTube ↗",
      },
      newsletter: {
        kicker: "Newsletter",
        title: "Caderno de Campo",
        subtitle: "Uma carta curta, a cada duas sextas, sobre o que eu estou construindo, lendo e aprendendo. Sem spam, sem afiliados.",
        placeholder: "seu@email.com",
        cta: "Assinar",
        footnote: "1.427 leitores · 62% open rate · cancelar é um clique",
        compact_cta: "Assinar a newsletter",
        compact_sub: "1 email a cada 2 sextas.",
      },
      about: {
        kicker: "Sobre",
        title: "Thiago Figueiredo",
        body: "Dev indie em Belo Horizonte. Há seis anos escrevo software; desde 2024 só pra mim mesmo. Seis apps no forno, um canal no YouTube, e este caderno aberto.",
        cta: "Ler bio completa →",
      },
      by_category: "Por categoria",
      min_read: "min",
      by: "por",
      read_more: "Ler →",
      all_articles: "Ver todos os artigos →",
      search_placeholder: "Buscar textos…",
      category_view: "Ver categoria →",
      post: {
        back: "← voltar ao arquivo",
        toc_title: "Neste texto",
        published: "Publicado",
        updated: "Atualizado",
        updated_short: "atualizado em",
        read_time: "min leitura",
        time_left: "restantes",
        back_to_top: "topo ↑",
        key_points_title: "Pontos-chave",
        key_points: [
          "Um caderno, não um produto",
          "Ritmo sem rigidez — semanal quando dá",
          "CMS próprio: um artigo, muitos destinos",
          "Monetização indireta via Vagalume",
          "Direito de parar sem culpa",
        ],
        pullquote_text: '"um caderno, não um produto"',
        pullquote_attr: "promessa 3",
        highlights_title: "Seus destaques",
        highlights_empty: "Selecione um trecho pra destacar.",
        highlights_clear: "Limpar tudo",
        highlights_hint: "Destacar",
        engagement: {
          views: "leituras",
          like: "curtir",
          liked: "curtido",
          bookmark: "salvar",
          bookmarked: "salvo",
          author_reply: "resposta do autor",
        },
        ai: {
          open: "Ler com IA",
          open_sub: "Resumo, explicação, conversa",
          title: "Leitura assistida",
          close: "Fechar",
          powered: "Respostas geradas por IA. Pode errar — o original é o que vale.",
          tab_summary: "TL;DR",
          tab_explain: "Explicar",
          tab_chat: "Conversar",
          summary_intro: "Gerar um resumo em três parágrafos deste texto:",
          summary_cta: "Gerar resumo",
          summary_loading: "Lendo o texto e resumindo…",
          summary_again: "Gerar de novo",
          explain_intro: "Explicar em linguagem mais simples. Quer com qual nível de profundidade?",
          explain_levels: ["ELI5", "Iniciante", "Intermediário"],
          explain_cta: "Explicar",
          explain_loading: "Reformulando com linguagem mais simples…",
          chat_intro: "Faça uma pergunta sobre o texto. Eu respondo com base só no que está escrito aqui.",
          chat_placeholder: "Ex: qual é a promessa 2?",
          chat_send: "Perguntar",
          chat_loading: "Pensando…",
          chat_suggestions: [
            "Qual é a ideia principal?",
            "Por que ele escolheu construir o próprio CMS?",
            "Explica a promessa 3",
          ],
          error: "Algo deu errado. Tenta de novo.",
        },
        series_kicker: "Parte da série",
        series_of: "de",
        series_next: "Próximo:",
        series_prev: "Anterior:",
        share: "Compartilhar",
        share_x: "Postar no X",
        share_ln: "Compartilhar no LinkedIn",
        share_copy: "Copiar link",
        share_copied: "Copiado ✓",
        tags_title: "Marcadores",
        author_title: "Sobre quem escreveu",
        author_more: "mais textos de Thiago →",
        related_title: "Textos relacionados",
        related_sub: "Mais na mesma categoria",
        next_in_series_title: "Continua na próxima parte",
        comments_title: "Conversa",
        comments_count: "comentários",
        comment_placeholder: "Deixe um comentário honesto (sem self-promo)",
        comment_submit: "Publicar",
        comment_sign_in: "Você precisa entrar com email pra comentar — protege do spam.",
        comment_likes: "curtidas",
        comment_reply: "responder",
        newsletter_inline_title: "Gostou? Recebe os próximos na caixa de entrada.",
        newsletter_inline_cta: "Assinar Caderno de Campo",
        colophon_title: "Colofão",
        colophon_body: "Escrito em <i>iA Writer</i> numa MacBook Air M2. Publicado pelo CMS que eu mesmo construí, que roda em Supabase + Vercel. Tipografia: Source Serif 4 para corpo, Inter pro resto. Ilustração de capa desenhada em SVG direto no código — sem stock photo, sem Midjourney.",
        footnotes_title: "Notas",
        footnote_label: "Nota",
      },
    },
    en: {
      brand_short: "bythiagofigueiredo",
      brand_tagline: "Written, coded and published from Brazil — by Thiago Figueiredo.",
      nav: {
        home: "Home",
        writing: "Writing",
        categories: "Categories",
        videos: "Videos",
        about: "About",
        contact: "Contact",
        newsletter: "Newsletter",
        dev: "Dev site",
      },
      hero: {
        kicker: "Featured",
        read_cta: "Read article",
      },
      latest: {
        title: "Latest writing",
        subtitle: "Everything I've written in the last few weeks, newest first.",
        all_cta: "See all writing →",
      },
      most_read: "Most read",
      most_read_sub: "Last 30 days",
      videos: {
        kicker: "Videos",
        title: "Latest from the channel",
        cta: "Open YouTube channel ↗",
      },
      newsletter: {
        kicker: "Newsletter",
        title: "Field Notes",
        subtitle: "A short letter, every other Friday, about what I'm building, reading, and learning. No spam, no affiliates.",
        placeholder: "you@email.com",
        cta: "Subscribe",
        footnote: "1,427 readers · 62% open rate · unsubscribe is one click",
        compact_cta: "Subscribe to the newsletter",
        compact_sub: "1 email every other Friday.",
      },
      about: {
        kicker: "About",
        title: "Thiago Figueiredo",
        body: "Indie dev in Brazil. Six years writing software; since 2024 only for myself. Six apps cooking, a YouTube channel, and this open notebook.",
        cta: "Read full bio →",
      },
      by_category: "By category",
      min_read: "min",
      by: "by",
      read_more: "Read →",
      all_articles: "See all articles →",
      search_placeholder: "Search writing…",
      category_view: "View category →",
      post: {
        back: "← back to archive",
        toc_title: "In this piece",
        published: "Published",
        updated: "Updated",
        updated_short: "updated",
        read_time: "min read",
        time_left: "left",
        back_to_top: "top ↑",
        key_points_title: "Key points",
        key_points: [
          "A notebook, not a product",
          "Rhythm without rigidity — weekly when possible",
          "Own CMS: one article, many destinations",
          "Indirect monetization via Vagalume",
          "The right to stop without guilt",
        ],
        pullquote_text: '"a notebook, not a product"',
        pullquote_attr: "promise 3",
        highlights_title: "Your highlights",
        highlights_empty: "Select a passage to highlight.",
        highlights_clear: "Clear all",
        highlights_hint: "Highlight",
        engagement: {
          views: "reads",
          like: "like",
          liked: "liked",
          bookmark: "save",
          bookmarked: "saved",
          author_reply: "author reply",
        },
        ai: {
          open: "Read with AI",
          open_sub: "Summary, explanation, chat",
          title: "Assisted reading",
          close: "Close",
          powered: "AI-generated answers. Can be wrong — the original text is what counts.",
          tab_summary: "TL;DR",
          tab_explain: "Explain",
          tab_chat: "Chat",
          summary_intro: "Generate a three-paragraph summary of this piece:",
          summary_cta: "Generate summary",
          summary_loading: "Reading and summarizing…",
          summary_again: "Generate again",
          explain_intro: "Rephrase in plainer language. What depth do you want?",
          explain_levels: ["ELI5", "Beginner", "Intermediate"],
          explain_cta: "Explain",
          explain_loading: "Rephrasing in simpler terms…",
          chat_intro: "Ask a question about the text. I'll answer based only on what's written here.",
          chat_placeholder: "e.g. what's promise 2?",
          chat_send: "Ask",
          chat_loading: "Thinking…",
          chat_suggestions: [
            "What's the main idea?",
            "Why did he build his own CMS?",
            "Explain promise 3",
          ],
          error: "Something went wrong. Try again.",
        },
        series_kicker: "Part of the series",
        series_of: "of",
        series_next: "Next:",
        series_prev: "Previous:",
        share: "Share",
        share_x: "Post on X",
        share_ln: "Share on LinkedIn",
        share_copy: "Copy link",
        share_copied: "Copied ✓",
        tags_title: "Tags",
        author_title: "About the author",
        author_more: "more from Thiago →",
        related_title: "Related writing",
        related_sub: "More in the same category",
        next_in_series_title: "Continues in the next part",
        comments_title: "Conversation",
        comments_count: "comments",
        comment_placeholder: "Leave an honest comment (no self-promo)",
        comment_submit: "Post",
        comment_sign_in: "You need to sign in with an email to comment — keeps the spam out.",
        comment_likes: "likes",
        comment_reply: "reply",
        newsletter_inline_title: "Liked it? Get the next one in your inbox.",
        newsletter_inline_cta: "Subscribe to Field Notes",
        colophon_title: "Colophon",
        colophon_body: "Written in <i>iA Writer</i> on a MacBook Air M2. Published by the CMS I built myself, running on Supabase + Vercel. Typography: Source Serif 4 for body, Inter for the rest. Header illustration drawn in SVG straight in the code — no stock photo, no Midjourney.",
        footnotes_title: "Notes",
        footnote_label: "Note",
      },
    },
  },
};

// Helper used by all directions: produce image style for a post
window.postImg = function(img, opts = {}) {
  const { dark = false, tall = false } = opts;
  const L1 = dark ? 22 : 62;
  const L2 = dark ? 12 : 42;
  const s1 = dark ? 45 : 55;
  const s2 = dark ? 35 : 45;
  const grad = `linear-gradient(${tall ? "165deg" : "135deg"}, hsl(${img.h}, ${s1}%, ${L1}%) 0%, hsl(${img.h2 ?? img.h + 40}, ${s2}%, ${L2}%) 100%)`;
  return { background: grad };
};

// Overlay pattern SVG (returns JSX-ready markup via string, but better to inline)
window.postPattern = function(pattern, color) {
  switch (pattern) {
    case "dots":
      return (
        '<pattern id="pdots" width="12" height="12" patternUnits="userSpaceOnUse">' +
        '<circle cx="6" cy="6" r="1.2" fill="' + color + '" opacity="0.35"/></pattern>'
      );
    case "grid":
      return (
        '<pattern id="pgrid" width="16" height="16" patternUnits="userSpaceOnUse">' +
        '<path d="M 16 0 L 0 0 0 16" fill="none" stroke="' + color + '" stroke-width="0.5" opacity="0.3"/></pattern>'
      );
    case "diag":
      return (
        '<pattern id="pdiag" width="10" height="10" patternUnits="userSpaceOnUse" patternTransform="rotate(45)">' +
        '<line x1="0" y1="0" x2="0" y2="10" stroke="' + color + '" stroke-width="1" opacity="0.25"/></pattern>'
      );
    case "stripe":
      return (
        '<pattern id="pstripe" width="30" height="8" patternUnits="userSpaceOnUse">' +
        '<rect width="30" height="4" fill="' + color + '" opacity="0.2"/></pattern>'
      );
    case "blur":
    default:
      return "";
  }
};
