import type { ConnectionHealth } from '@/lib/social/actions'
import type { FeedItem } from './feed-grid'

export const MOCK_CONNECTIONS: ConnectionHealth[] = [
  {
    connectionId: 'mock-ig',
    provider: 'instagram',
    accountName: '@thiago.figueiredo',
    status: 'ok',
    followersCount: 8420,
    tokenExpiresIn: 45,
  },
  {
    connectionId: 'mock-yt',
    provider: 'youtube',
    accountName: 'Comunidade ativa',
    status: 'ok',
    followersCount: 1160,
    tokenExpiresIn: null,
  },
  {
    connectionId: 'mock-fb',
    provider: 'facebook',
    accountName: 'Thiago Figueiredo',
    status: 'warn',
    followersCount: null,
    tokenExpiresIn: 6,
  },
]

export const MOCK_FEED_ITEMS: FeedItem[] = [
  {
    id: 'mock-1',
    status: 'completed',
    title: 'Edicao 042 no ar',
    imageUrl: null,
    scheduledAt: null,
    publishedAt: '2026-05-22T14:26:00Z',
    destId: 'ig_story',
    destLabel: 'Story',
    provider: 'instagram',
    statusLabel: 'No ar',
  },
  {
    id: 'mock-2',
    status: 'completed',
    title: 'Video novo no ar — Fui ao MBK Center comparar o preco do ouro — o resultado...',
    imageUrl: null,
    scheduledAt: null,
    publishedAt: '2026-05-19T20:26:00Z',
    destId: 'yt_community',
    destLabel: 'Comunidade',
    provider: 'youtube',
    statusLabel: 'No ar',
  },
  {
    id: 'mock-3',
    status: 'completed',
    title: 'Qual conteudo voce quer ver primeiro essa semana?',
    imageUrl: null,
    scheduledAt: null,
    publishedAt: '2026-05-19T19:47:00Z',
    destId: 'yt_community',
    destLabel: 'Comunidade',
    provider: 'youtube',
    statusLabel: 'No ar',
  },
  {
    id: 'mock-4',
    status: 'completed',
    title: 'Em 2009 eu xingava em ingles quebrado. Em 2017 tirei 91 no TOEFL sem nenhuma...',
    imageUrl: null,
    scheduledAt: null,
    publishedAt: '2026-05-19T19:37:00Z',
    destId: 'fb_page',
    destLabel: 'Fanpage',
    provider: 'facebook',
    statusLabel: 'No ar',
  },
  {
    id: 'mock-5',
    status: 'completed',
    title: 'Story preview',
    imageUrl: null,
    scheduledAt: null,
    publishedAt: '2026-05-19T19:24:00Z',
    destId: 'ig_story',
    destLabel: 'Story',
    provider: 'instagram',
    statusLabel: 'No ar',
  },
  {
    id: 'mock-6',
    status: 'scheduled',
    title: 'New on the blog',
    imageUrl: null,
    scheduledAt: '2026-05-20T09:05:00Z',
    publishedAt: null,
    destId: 'ig_story',
    destLabel: 'Story',
    provider: 'instagram',
    statusLabel: 'Agendado',
  },
]
